Add the abbreviation column to the raw data home_school_state.

```{r}
# add columns to home_school_state.csv
# read the state csv
school_state <- read.csv("../../data/derived/state_update.csv")
school_state
states_abbre <- read.csv("../../data/derived/states_abbreviation.csv")
states_abbre
```

```{r}
#' Add State Abbreviation to Data Frame
#'
#' This function takes a data frame and adds a new column with state abbreviations.
#' The state names in the data frame are matched against a webscraping data frame
#' containing state names and their corresponding abbreviations. Matching is case-insensitive.
#' If no abbreviation is found for a state, the full state name is used.
#'
#' @param data_frame A data frame that contains a column with state names.
#' @param state_col_name The name of the column in data_frame that contains the state names.
#' @param states_abbre A data frame with two columns: 'US.STATE' with full state names
#'        and 'POSTAL.ABBREVIATION' with the corresponding state abbreviations.
#'
#' @return The original data_frame with an additional column named 'Abbreviation'.
#' @export
#' @examples
#' # Assuming states_abbre is a dataframe contains both the states ant the abbreviation
#' # df is a data frame with a column "state_name" that contains state names
#' df_with_abbreviations <- add_state_abbreviation(df, "state_name", states_abbre)
add_state_abbreviation <- function(data_frame, state_col_name, states_abbre) {
  # Convert to uppercase 
  state_names_upper <- toupper(data_frame[[state_col_name]])
  states_abbre_upper <- toupper(states_abbre$US.STATE)
  
  # Match the uppercase state names to find corresponding indices in states_abbre
  indices <- match(state_names_upper, states_abbre_upper)
  abbreviations <- states_abbre$POSTAL.ABBREVIATION[indices]
  
  # Substitute NA values with the original state name from data_frame
  abbreviations[is.na(abbreviations)] <- data_frame[[state_col_name]][is.na(abbreviations)]
  
  # Add the abbreviation data as a new column 
  data_frame$Abbreviation <- abbreviations
  
  return(data_frame)
}
```


```{r}
state_update <- add_state_abbreviation(school_state, "state",states_abbre)
# since the District of Columbia does not find out the abbreviation from the table, I manually change it. 
state_update$Abbreviation[state_update$state == "DISTRICT OF COLUMBIA"] = "DC"
state_update 
```
```{r}
#convert year 
state_update$year <- sub("^(....)-.*", "\\1", state_update$year)
state_update
```


save the data to derived folder
```{r}
write.csv(state_update, "../../data/derived/state_update.csv", row.names = FALSE)
```




